## Matrix Operations

Matrix is a two-dimensional array that contains numbers. 

In [3]:
import numpy as np

matrix_A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

matrix_A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Matrix operations - Addition

In [4]:
matrix_B = np.array([[2, 3, 4], [3, 4, 5], [4, 5, 6]])

add_A_B = matrix_A + matrix_B

add_A_B

array([[ 3,  5,  7],
       [ 7,  9, 11],
       [11, 13, 15]])

### Matrix Operations - Subraction

In [5]:
subtract_A_B = matrix_A - matrix_B

subtract_A_B

array([[-1, -1, -1],
       [ 1,  1,  1],
       [ 3,  3,  3]])

### Matrix Operations - Multiplication

In [6]:
multiply_A_B = matrix_A * matrix_B

multiply_A_B

array([[ 2,  6, 12],
       [12, 20, 30],
       [28, 40, 54]])

### Matrix Operations - Division

Matrix Inverse helps to perform division. The inverse of matrix A multiplies with A yields the identity matrix. The identity matrix in the world of matrices is equivalent to the number 1, and any matrix multiplied by the identity matrix returns the original matrix.

In [7]:
# Finding the inverse of matrix (multiply_A_B)

divide_A_B = np.linalg.inv(multiply_A_B)

divide_A_B

array([[ 2.5       , -3.25      ,  1.25      ],
       [-4.        ,  4.75      , -1.75      ],
       [ 1.66666667, -1.83333333,  0.66666667]])

In [9]:
# Finding the pseduo-inverse of matrix of A

pseduo_inverse_A = np.linalg.pinv(matrix_A)

pseduo_inverse_A

array([[-6.38888889e-01, -1.66666667e-01,  3.05555556e-01],
       [-5.55555556e-02,  3.36727575e-17,  5.55555556e-02],
       [ 5.27777778e-01,  1.66666667e-01, -1.94444444e-01]])

### Matrix Operations - Transpose

The transpose of a matrix is an operator that flips a matrix over its diagonal, i.e., it switches the row and column indices of the matrix by producing another matrix denoted as \(A^T\).
 
In numpy, you can get the transpose of a matrix using the `.T` attribute.

In [10]:
transpose_val = np.transpose(matrix_A)

transpose_val

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [11]:
transpose_val.T

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
feature_1 = np.array([[123], [456], [789]])
feature_2 = np.array([[234], [567], [890]])

# Combine the two features into one matrix horizontally. 

data_features = np.hstack((feature_1, feature_2))
print(data_features)


[[123 234]
 [456 567]
 [789 890]]


In [15]:
# normalize data - put all the values into 0 to 1 range.

normalized_data_features = data_features / np.linalg.norm(data_features)

normalized_data_features

array([[0.0866728 , 0.16488971],
       [0.32132354, 0.39954046],
       [0.55597429, 0.62714464]])

In [16]:
# Min Max Normalization

normalized_data_features = (data_features - np.min(data_features)) / (np.max(data_features) - np.min(data_features))

normalized_data_features

array([[0.        , 0.14471969],
       [0.43415906, 0.57887875],
       [0.86831812, 1.        ]])

In [17]:
# Simulate the weights of features
weights = np.array([0.4, 0.6])

# Calculate the weighted sum of features
weighted_sum_features = np.dot(data_features, weights)
print(weighted_sum_features)

[189.6 522.6 849.6]
