# Creating a Numpy Array

In [2]:
# Import Package

import numpy as np

## One Dimentional NumPy Array Creation

In [3]:
# Regular Python list to one dimentional NumPy Array

# Create a Python list
py_list = [1, 2, 3, 4, 5]

# Convert list to a Numpy array
np_array = np.array(py_list)

print(np_array) # Output: [1 2 3 4 5]

[1 2 3 4 5]


## Two Dimentional NumPy Array Creation

In [4]:
# Create a 2D Python list
py_2dim_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# Convert list to a Numpy array
np_2dim_array = np.array(py_2dim_list)

print(np_2dim_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Attributes of NumPy Array

In [5]:
# ndim - The number of dimensions of the array.
print("Dimensions: ", np_2dim_array.ndim) # Dimensions:  2

# The size of each dimension
print("Shape: ", np_2dim_array.shape)     # Shape:  (3, 3)

# The total number of elements in the array.
print("Size: ", np_2dim_array.size)       # Size: 9 because ( 3 x 3 )

# The data type of the elements in the array.
print("Data Type: ", np_2dim_array.dtype) # Data Type:  int64

Dimensions:  2
Shape:  (3, 3)
Size:  9
Data Type:  int64


## Array Manipulations

In [22]:
# Indexing: specific positions (indexing) 
print("Indexed Value: ", np_2dim_array[1, 2]) # Indexed Value:  6

# Slicing: slices of the array
print("Sliced Value: ", np_2dim_array[0,1:3]) # Sliced Value:  [2 3]

# Reshape: Change the shape of the 1D array to 2D array (the reshape size should match the original size)
reshaped_array = np_array.reshape(5, 1)
print("Reshaped Array:\n", reshaped_array)

Indexed Value:  6
Sliced Value:  [2 3]
Reshaped Array:
 [[1]
 [2]
 [3]
 [4]
 [5]]


## Array Operations

In [24]:
numpy_array1 = np.array([0, 1, 2])
numpy_array2 = np.array([3, 4, 5])

# Add Two NumPy Arrays
print(numpy_array1 + numpy_array2) # Output:  [0 + 3, 1 + 4, 2 + 5] = [3, 5, 7]

# Subract NumPy Arrays
print(numpy_array1 - numpy_array2) # Output: [0 - 3, 1 - 4, 2 - 5] = [-3, -5, -7]

# Multiply NumPy Arrays
print(numpy_array1 * numpy_array2) # Output: [0 * 3, 1 * 4, 2 * 5] = [0, 4, 10]

# Divide NumPy Arrays
print(numpy_array1 / numpy_array2) # Output: [0 / 3, 1 / 4, 2 / 5] = [0, 0.25, 0.4]

[3 5 7]
[-3 -3 -3]
[ 0  4 10]
[0.   0.25 0.4 ]
